// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Article struct {
	ID        string      `json:"id"`
	Content   *string     `json:"content"`
	Title     *string     `json:"title"`
	Excerpt   *string     `json:"excerpt"`
	User      *User       `json:"user"`
	CreateAt  *time.Time  `json:"createAt"`
	UpdateAt  *time.Time  `json:"updateAt"`
	Categorys []*Category `json:"categorys"`
}

type Articles struct {
	Count    *int             `json:"count"`
	PageInfo *PageInfo        `json:"pageInfo"`
	Edges    []*ArticlesEdges `json:"edges"`
}

type ArticlesEdges struct {
	Node *Article `json:"node"`
}

type ArticlesFilter struct {
	Title    *string `json:"title"`
	Category *string `json:"category"`
	Deleted  *bool   `json:"deleted"`
	Asc      *bool   `json:"asc"`
}

type Category struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
