// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	User                 *UserResponse `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *UserResponse {
	if m != nil {
		return m.User
	}
	return nil
}

type UserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender               int64    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	CreateAt             string   `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Emial                string   `protobuf:"bytes,6,opt,name=emial,proto3" json:"emial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserResponse) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *UserResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserResponse) GetEmial() string {
	if m != nil {
		return m.Emial
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.user.LoginResponse")
	proto.RegisterType((*UserRequest)(nil), "go.micro.srv.user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "go.micro.srv.user.UserResponse")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.user.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.user.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.user.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.user.Pong")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x4e, 0xf2, 0x30,
	0x18, 0x65, 0x63, 0x1b, 0xfc, 0x1f, 0xfc, 0x7f, 0x7e, 0x1a, 0xd4, 0x65, 0x89, 0x48, 0xaa, 0x17,
	0x78, 0x33, 0x09, 0x3c, 0x81, 0x86, 0x1b, 0x13, 0x2e, 0xcc, 0x88, 0xf1, 0xba, 0x6e, 0xcd, 0xb2,
	0xe8, 0x5a, 0x6c, 0x0b, 0xbe, 0x88, 0xef, 0xe3, 0xab, 0x99, 0xb6, 0x9b, 0x12, 0x1c, 0x7a, 0xb3,
	0xec, 0xf4, 0x9c, 0x9e, 0x7d, 0xdf, 0x39, 0x19, 0x1c, 0xad, 0x05, 0x57, 0xfc, 0x6a, 0x23, 0xa9,
	0x30, 0x8f, 0xd8, 0x60, 0x34, 0xc8, 0x79, 0x5c, 0x16, 0xa9, 0xe0, 0xb1, 0x14, 0xdb, 0x58, 0x13,
	0x78, 0x01, 0xfd, 0x25, 0xcf, 0x0b, 0x96, 0xd0, 0x97, 0x0d, 0x95, 0x0a, 0x85, 0xd0, 0x21, 0x69,
	0xca, 0x37, 0x4c, 0x85, 0xce, 0xd8, 0x99, 0xfc, 0x49, 0x6a, 0x88, 0x22, 0xe8, 0xae, 0x89, 0x94,
	0xaf, 0x5c, 0x64, 0xa1, 0x6b, 0xa8, 0x4f, 0x8c, 0x17, 0xf0, 0xb7, 0x72, 0x91, 0x6b, 0xce, 0x24,
	0x45, 0x73, 0xf0, 0xb4, 0xbd, 0xf1, 0xe8, 0xcd, 0xce, 0xe2, 0x6f, 0x1f, 0x8e, 0xef, 0x25, 0x15,
	0xb5, 0x3c, 0x31, 0x62, 0x7c, 0x0a, 0x3d, 0x7b, 0x6a, 0x47, 0xf9, 0x07, 0x6e, 0x91, 0x19, 0x87,
	0x76, 0xe2, 0x16, 0x19, 0x7e, 0x73, 0xa0, 0xbf, 0x7b, 0x6b, 0x5f, 0x80, 0x10, 0x78, 0x8c, 0x94,
	0xb4, 0x9a, 0xce, 0xbc, 0xa3, 0x63, 0x08, 0x72, 0xca, 0x32, 0x2a, 0xc2, 0xb6, 0xd1, 0x55, 0x48,
	0x6f, 0x93, 0x0a, 0x4a, 0x14, 0xbd, 0x56, 0xa1, 0x67, 0xb7, 0xa9, 0xb1, 0xbe, 0x43, 0xb6, 0x44,
	0x11, 0x11, 0xfa, 0x86, 0xa9, 0x10, 0x1a, 0x82, 0x4f, 0xcb, 0x82, 0x3c, 0x87, 0x81, 0x39, 0xb6,
	0x00, 0x4f, 0xe0, 0xff, 0x4a, 0x09, 0x4a, 0xca, 0x82, 0xe5, 0xf5, 0xe8, 0x43, 0xf0, 0xbf, 0x32,
	0x6c, 0x27, 0x16, 0xe0, 0x4b, 0x18, 0xec, 0x28, 0xab, 0x25, 0x9a, 0xa5, 0x23, 0xf0, 0xee, 0x0a,
	0x96, 0xeb, 0x51, 0xa4, 0x12, 0xfc, 0x89, 0x56, 0x74, 0x85, 0x0c, 0xcf, 0x0f, 0xf3, 0xb3, 0x77,
	0x17, 0x3a, 0x3a, 0xab, 0x95, 0xd8, 0xa2, 0x25, 0xf8, 0xa6, 0x1c, 0xd4, 0x54, 0xc3, 0x6e, 0xf9,
	0xd1, 0xf8, 0xb0, 0xc0, 0x4e, 0x8b, 0x5b, 0xe8, 0x16, 0x3c, 0x6d, 0x8c, 0x46, 0x07, 0x3b, 0xb5,
	0x5e, 0xbf, 0x75, 0x8e, 0x5b, 0xe8, 0x01, 0x02, 0x9b, 0x07, 0x3a, 0x6f, 0x10, 0xef, 0x87, 0x1a,
	0x5d, 0xfc, 0x2c, 0xaa, 0x6d, 0xa7, 0x0e, 0xba, 0x81, 0xae, 0x4e, 0xcf, 0x24, 0x74, 0xd2, 0x70,
	0x4b, 0x93, 0x51, 0x23, 0xc1, 0x59, 0x8e, 0x5b, 0x13, 0x67, 0xea, 0x3c, 0x06, 0xe6, 0x97, 0x99,
	0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x26, 0x70, 0x71, 0x4b, 0x03, 0x00, 0x00,
}
