// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID     string  `json:"id"`
	Name   *string `json:"name"`
	Email  *string `json:"email"`
	Gender *int    `json:"gender"`
	Avatar *string `json:"avatar"`
}

func (User) IsEntity() {}
